### ISSUE TITLE
The parameters dictionary contains a null entry for parameter 'conversationID' of non-nullable type 'System.Int32' for method 'System.Web.Mvc.ActionResult Index(Int32)' in 'DataDrivenBot.Admin.Controllers.HomeController'. An optional parameter must be a reference type, a nullable type, or be declared as an optional parameter.

### ISSUE THREAD

**Issue by ADefWebserver** [JonathanHuss/DataDrivenBot#1]
When trying to run the DataDrivenBot.Admin project I get: 

> The parameters dictionary contains a null entry for parameter 'conversationID' of non-nullable type 'System.Int32' for method 'System.Web.Mvc.ActionResult Index(Int32)' in 'DataDrivenBot.Admin.Controllers.HomeController'. An optional parameter must be a reference type, a nullable type, or be declared as an optional parameter.
> Parameter name: parameters 

I created the database and even tried changing the controller method (that was throwing the error) to:

```
        public ActionResult Index(int? conversationID)
        {
            Diagram model = new Diagram();
            if (conversationID != null)
            {
                model = GetDiagramModel(conversationID.Value);
            }
            else
            {
                model = GetDiagramModel(0);
            }

            return View(model);
        }
```

But then I got errors because it is expecting the database to have data.

**Comment by JonathanHuss** [comment]
It's not production ready code.  It's just a concept, which means some of the data was loaded manually into the database during the exploration of the concept .  If it were to be productionized, it would definitely need some initialization code for an empty database.  Try adding a ConversationTemplate record to your database and then pass the ID of that ConversationTemplate when you load the diagram page, something like this (use whatever address and ID is relevant for you):  http://localhost:1444/?conversationID=1

**Comment by ADefWebserver** [comment]
Thanks Jonathan. I will give it a try this weekend. I really want to explore this because I think you are really on to an answer for a problem that few want to admit or talk about. Basically, normal C# coding becomes a spaghetti nightmare when trying to program even a medium complex bot. 

I think visualizations are the answer.
